spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: won9975744
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: ${job.name:createArticleJob}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true