server:
  port: 8005

spring:
  application:
    name: board-article-read-service
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: board-article-read-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
endpoints:
  board-article-service:
    url: http://localhost:8000
  board-comment-service:
    url: http://localhost:8001
  board-like-service:
    url: http://localhost:8002
  board-view-service:
    url: http://localhost:8003
