spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupang
    username: root
    password: won9975744
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true