#management:
#  tracing:
#    enabled: true

#logging:
#  pattern:
#    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} [%-0.32X{traceId:-},%-0.16X{spanId:-}] %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'

spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      observation-enabled: true
    listener:
      observation-enabled: true

management:
  tracing:
    enabled: true
    propagation:
      type: w3c   # frontend / backend 동일하게!
    sampling:
      probability: 1.0   # 테스트용 (100%)

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans